### ISSUE TITLE
[VDOP]: After wake from suspend or screen poweron after inactivity everything is pinned everywhere

### ISSUE THREAD

**Issue by iamalsonothere** [Ubiquitine/kwin-scripts#4]
Pretty much the title. After plasma turns off the displays because of inactivity or the PC goes into sleep, after wake up or display power on very often this script breaks itself and pins everything on every screen or gets confused and thinks the secondary display is primary. This occurs in 0.3.0 and 0.4.0, i was not able to figure out what to set the primary display setting string to in 0.2.0.

**Comment by Ubiquitine** [comment]
New branch and PR for testing the fix.
Please test  this by manually upgrading the script:

1. Clone the repo to you local machine
2. Switch to the testing branch: `git switch VDOP-testing`
3. Upgrade the script: `./helper.sh upgrade virtual-desktops-only-on-primary`

**Comment by Ubiquitine** [comment]
@iamalsonothere,
I was finally able to reproduce the issue by emulating multiple screen in VirtualBox and testing different scenarios when primary display goes off and back on again. 
Please test the latest v0.4.4 from VDOP-testing branch, using the steps from my previous comment.
Make sure to specify the "workspace.screens" index of you primary display in the scrip configuration if you primary display is not the first in the list. 

Laptop owners don't need to do this since the built-in display will always be the first in the list, and in most cases this display is  the one that is used as primary.

**Comment by iamalsonothere** [comment]
The latest 0.4.5 version from the testing branch pins every window on the secondary screen regardless of what index its set to.

If i can provide logs, please tell me how to obtain them and I will attach them here ( i have no experience with KDE addon dev )

**Comment by Ubiquitine** [comment]
It seems like you issue report is not complete.
Please, read this really great articles about reporting a bug:

1. ["How to Report Bugs Effectively" by by Simon Tatham](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html)
2. ["Writing a proper GitHub issue", by Andy Cochran](https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f)

Then, try to follow their guidelines to provide as much useful information as possible to help me reproduce and fix this.

**Comment by Ubiquitine** [comment]
I'm closing this issue since there were few version updates to this scrips which included some workaround for the original  issue. I cannot reproduce what you claim happens in your case anymore.
If you still have an issue, please try to collect as much information as possible about your system, what happens exactly, maybe some logs and/or screenshots.
